# alignment options
GENOME_FASTA: ../data/genome/dmel-all-chromosome-r6.22.fasta.masked
TRANSPOSON_FASTA: ../data/genome/dmel_repbase_lib.fasta
GENE_GTF: ftp://ftp.flybase.net/releases/FB2018_03/dmel_r6.22/gtf/dmel-all-r6.22.gtf.gz
